#===========================================
# TEST SPECIFIC SETTINGS (junit-tests)
#===========================================
spring:
  cache:
    type: none

#-------------------------------------------
# Lime integration settings
#-------------------------------------------
config:
  integration:
    lime:
      url: http://host.com
      apiKey: the-test-key

