integration:
  lime:
    connectTimeout: 10
    readTimeout: 20
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
resilience4j:
  circuitbreaker:
    instances:
      lime:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
spring:
  application:
    name: api-quotation-request
  cache:
    cache-names: helpdeskcategories,offices
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=86400s
springdoc:
  swagger-ui:
    operationsSorter: method
