#===========================================
# TEST SPECIFIC SETTINGS (junit-tests)
#===========================================
spring:
  cache:
    type: none

#-------------------------------------------
# Lime integration settings
#-------------------------------------------
# Feign client
integration:
  lime:
    url: http://host.com
    apiKey: the-test-key
